# Generated by Django 5.0.4 on 2024-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Ф.И.О.'),
        ),
    ]
