# Generated by Django 5.0.4 on 2024-05-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_client_owner_emailmessage_owner_emailsettings_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('disable_client', 'Can disable client')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
