# Generated by Django 5.0.4 on 2024-05-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'permissions': [('disable_mailing', 'Can disable mailing')], 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
