# Generated by Django 5.0.4 on 2024-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_emailsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
    ]
