# Generated by Django 5.0.4 on 2024-05-06 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='first_datetime',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='clients',
            field=models.ManyToManyField(to='mail.client', verbose_name='Кому (клиенты сервиса)'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания рассылки'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='date_next',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата следующей рассылки'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начала рассылки'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активация рассылки'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.emailmessage', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время рассылки'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='periodicity',
            field=models.CharField(choices=[('PD', 'Раз в день'), ('PW', 'Раз в неделю'), ('PM', 'Раз в месяц'), ('PY', 'Раз в год')], default='PD', max_length=2, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('RUN', 'Запущена'), ('CLOSE', 'Завершена'), ('ERROR', 'Ошибка')], default='CREATED', max_length=10, verbose_name='статус'),
        ),
    ]
